
#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group_id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer